name: Test Backend
on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Build and test with Maven + SonarCloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=LindaMohamed_devops-s8 -Dsonar.organization=lindamohamed -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        working-directory: backend/simple-api-student-main